export interface DrawWord {
  word: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const DRAW_WORD_BANK: DrawWord[] = [
  // Lako — svakodnevni pojmovi, jednostavni oblici
  { word: 'sunce', difficulty: 'easy' },
  { word: 'mačka', difficulty: 'easy' },
  { word: 'pas', difficulty: 'easy' },
  { word: 'kuća', difficulty: 'easy' },
  { word: 'drvo', difficulty: 'easy' },
  { word: 'auto', difficulty: 'easy' },
  { word: 'riba', difficulty: 'easy' },
  { word: 'lopta', difficulty: 'easy' },
  { word: 'zvezda', difficulty: 'easy' },
  { word: 'mesec', difficulty: 'easy' },
  { word: 'cvet', difficulty: 'easy' },
  { word: 'jabuka', difficulty: 'easy' },
  { word: 'srce', difficulty: 'easy' },
  { word: 'oko', difficulty: 'easy' },
  { word: 'knjiga', difficulty: 'easy' },
  { word: 'šešir', difficulty: 'easy' },
  { word: 'šolja', difficulty: 'easy' },
  { word: 'cipela', difficulty: 'easy' },
  { word: 'ptica', difficulty: 'easy' },
  { word: 'oblak', difficulty: 'easy' },
  { word: 'kiša', difficulty: 'easy' },
  { word: 'torta', difficulty: 'easy' },
  { word: 'čamac', difficulty: 'easy' },
  { word: 'vrata', difficulty: 'easy' },
  { word: 'ključ', difficulty: 'easy' },
  { word: 'pica', difficulty: 'easy' },
  { word: 'osmeh', difficulty: 'easy' },
  { word: 'jaje', difficulty: 'easy' },
  { word: 'sladoled', difficulty: 'easy' },
  { word: 'banana', difficulty: 'easy' },
  { word: 'sat', difficulty: 'easy' },
  { word: 'lampa', difficulty: 'easy' },
  { word: 'stolica', difficulty: 'easy' },
  { word: 'krevet', difficulty: 'easy' },
  { word: 'kašika', difficulty: 'easy' },

  // Srednje — specifičniji pojmovi, traže više detalja
  { word: 'gitara', difficulty: 'medium' },
  { word: 'avion', difficulty: 'medium' },
  { word: 'zamak', difficulty: 'medium' },
  { word: 'zmaj', difficulty: 'medium' },
  { word: 'robot', difficulty: 'medium' },
  { word: 'sneško', difficulty: 'medium' },
  { word: 'gusar', difficulty: 'medium' },
  { word: 'raketa', difficulty: 'medium' },
  { word: 'leptir', difficulty: 'medium' },
  { word: 'dinosaurus', difficulty: 'medium' },
  { word: 'pauk', difficulty: 'medium' },
  { word: 'slon', difficulty: 'medium' },
  { word: 'pingvin', difficulty: 'medium' },
  { word: 'vulkan', difficulty: 'medium' },
  { word: 'duga', difficulty: 'medium' },
  { word: 'blago', difficulty: 'medium' },
  { word: 'kamera', difficulty: 'medium' },
  { word: 'bicikl', difficulty: 'medium' },
  { word: 'kišobran', difficulty: 'medium' },
  { word: 'sendvič', difficulty: 'medium' },
  { word: 'hamburger', difficulty: 'medium' },
  { word: 'svetionik', difficulty: 'medium' },
  { word: 'vodopad', difficulty: 'medium' },
  { word: 'teleskop', difficulty: 'medium' },
  { word: 'pečurka', difficulty: 'medium' },
  { word: 'logorska vatra', difficulty: 'medium' },
  { word: 'kruna', difficulty: 'medium' },
  { word: 'mač', difficulty: 'medium' },
  { word: 'sidro', difficulty: 'medium' },
  { word: 'merdevine', difficulty: 'medium' },
  { word: 'most', difficulty: 'medium' },
  { word: 'pahulja', difficulty: 'medium' },
  { word: 'šlem', difficulty: 'medium' },
  { word: 'kengur', difficulty: 'medium' },
  { word: 'hobotnica', difficulty: 'medium' },

  // Teško — apstraktni pojmovi, izazovni za crtanje
  { word: 'sloboda', difficulty: 'hard' },
  { word: 'noćna mora', difficulty: 'hard' },
  { word: 'ljubomora', difficulty: 'hard' },
  { word: 'gravitacija', difficulty: 'hard' },
  { word: 'tišina', difficulty: 'hard' },
  { word: 'rok', difficulty: 'hard' },
  { word: 'lozinka', difficulty: 'hard' },
  { word: 'nostalgija', difficulty: 'hard' },
  { word: 'nevidljiv', difficulty: 'hard' },
  { word: 'eho', difficulty: 'hard' },
  { word: 'zagađenje', difficulty: 'hard' },
  { word: 'evolucija', difficulty: 'hard' },
  { word: 'kamuflaža', difficulty: 'hard' },
  { word: 'nestanak struje', difficulty: 'hard' },
  { word: 'zemljotres', difficulty: 'hard' },
  { word: 'glavobolja', difficulty: 'hard' },
  { word: 'opekotina od sunca', difficulty: 'hard' },
  { word: 'gužva u saobraćaju', difficulty: 'hard' },
  { word: 'putovanje kroz vreme', difficulty: 'hard' },
  { word: 'mesečarenje', difficulty: 'hard' },
  { word: 'ispiranje mozga', difficulty: 'hard' },
  { word: 'nostalgija za domom', difficulty: 'hard' },
  { word: 'nož u leđa', difficulty: 'hard' },
  { word: 'oluja ideja', difficulty: 'hard' },
  { word: 'žrtveni jarac', difficulty: 'hard' },
];
