import type { Language } from '../i18n/types.js';

export interface DrawWord {
  word: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const DRAW_WORD_BANK: DrawWord[] = [
  // Lako — svakodnevni pojmovi, jednostavni oblici
  { word: 'sunce', difficulty: 'easy' },
  { word: 'mačka', difficulty: 'easy' },
  { word: 'pas', difficulty: 'easy' },
  { word: 'kuća', difficulty: 'easy' },
  { word: 'drvo', difficulty: 'easy' },
  { word: 'auto', difficulty: 'easy' },
  { word: 'riba', difficulty: 'easy' },
  { word: 'lopta', difficulty: 'easy' },
  { word: 'zvezda', difficulty: 'easy' },
  { word: 'mesec', difficulty: 'easy' },
  { word: 'cvet', difficulty: 'easy' },
  { word: 'jabuka', difficulty: 'easy' },
  { word: 'srce', difficulty: 'easy' },
  { word: 'oko', difficulty: 'easy' },
  { word: 'knjiga', difficulty: 'easy' },
  { word: 'šešir', difficulty: 'easy' },
  { word: 'šolja', difficulty: 'easy' },
  { word: 'cipela', difficulty: 'easy' },
  { word: 'ptica', difficulty: 'easy' },
  { word: 'oblak', difficulty: 'easy' },
  { word: 'kiša', difficulty: 'easy' },
  { word: 'torta', difficulty: 'easy' },
  { word: 'čamac', difficulty: 'easy' },
  { word: 'vrata', difficulty: 'easy' },
  { word: 'ključ', difficulty: 'easy' },
  { word: 'pica', difficulty: 'easy' },
  { word: 'osmeh', difficulty: 'easy' },
  { word: 'jaje', difficulty: 'easy' },
  { word: 'sladoled', difficulty: 'easy' },
  { word: 'banana', difficulty: 'easy' },
  { word: 'sat', difficulty: 'easy' },
  { word: 'lampa', difficulty: 'easy' },
  { word: 'stolica', difficulty: 'easy' },
  { word: 'krevet', difficulty: 'easy' },
  { word: 'kašika', difficulty: 'easy' },

  // Srednje — specifičniji pojmovi, traže više detalja
  { word: 'gitara', difficulty: 'medium' },
  { word: 'avion', difficulty: 'medium' },
  { word: 'zamak', difficulty: 'medium' },
  { word: 'zmaj', difficulty: 'medium' },
  { word: 'robot', difficulty: 'medium' },
  { word: 'sneško', difficulty: 'medium' },
  { word: 'gusar', difficulty: 'medium' },
  { word: 'raketa', difficulty: 'medium' },
  { word: 'leptir', difficulty: 'medium' },
  { word: 'dinosaurus', difficulty: 'medium' },
  { word: 'pauk', difficulty: 'medium' },
  { word: 'slon', difficulty: 'medium' },
  { word: 'pingvin', difficulty: 'medium' },
  { word: 'vulkan', difficulty: 'medium' },
  { word: 'duga', difficulty: 'medium' },
  { word: 'blago', difficulty: 'medium' },
  { word: 'kamera', difficulty: 'medium' },
  { word: 'bicikl', difficulty: 'medium' },
  { word: 'kišobran', difficulty: 'medium' },
  { word: 'sendvič', difficulty: 'medium' },
  { word: 'hamburger', difficulty: 'medium' },
  { word: 'svetionik', difficulty: 'medium' },
  { word: 'vodopad', difficulty: 'medium' },
  { word: 'teleskop', difficulty: 'medium' },
  { word: 'pečurka', difficulty: 'medium' },
  { word: 'logorska vatra', difficulty: 'medium' },
  { word: 'kruna', difficulty: 'medium' },
  { word: 'mač', difficulty: 'medium' },
  { word: 'sidro', difficulty: 'medium' },
  { word: 'merdevine', difficulty: 'medium' },
  { word: 'most', difficulty: 'medium' },
  { word: 'pahulja', difficulty: 'medium' },
  { word: 'šlem', difficulty: 'medium' },
  { word: 'kengur', difficulty: 'medium' },
  { word: 'hobotnica', difficulty: 'medium' },

  // Teško — apstraktni pojmovi, izazovni za crtanje
  { word: 'sloboda', difficulty: 'hard' },
  { word: 'noćna mora', difficulty: 'hard' },
  { word: 'ljubomora', difficulty: 'hard' },
  { word: 'gravitacija', difficulty: 'hard' },
  { word: 'tišina', difficulty: 'hard' },
  { word: 'rok', difficulty: 'hard' },
  { word: 'lozinka', difficulty: 'hard' },
  { word: 'nostalgija', difficulty: 'hard' },
  { word: 'nevidljiv', difficulty: 'hard' },
  { word: 'eho', difficulty: 'hard' },
  { word: 'zagađenje', difficulty: 'hard' },
  { word: 'evolucija', difficulty: 'hard' },
  { word: 'kamuflaža', difficulty: 'hard' },
  { word: 'nestanak struje', difficulty: 'hard' },
  { word: 'zemljotres', difficulty: 'hard' },
  { word: 'glavobolja', difficulty: 'hard' },
  { word: 'opekotina od sunca', difficulty: 'hard' },
  { word: 'gužva u saobraćaju', difficulty: 'hard' },
  { word: 'putovanje kroz vreme', difficulty: 'hard' },
  { word: 'mesečarenje', difficulty: 'hard' },
  { word: 'ispiranje mozga', difficulty: 'hard' },
  { word: 'nostalgija za domom', difficulty: 'hard' },
  { word: 'nož u leđa', difficulty: 'hard' },
  { word: 'oluja ideja', difficulty: 'hard' },
  { word: 'žrtveni jarac', difficulty: 'hard' },
];

export const DRAW_WORD_BANK_EN: DrawWord[] = [
  // Easy — everyday concepts, simple shapes
  { word: 'sun', difficulty: 'easy' },
  { word: 'cat', difficulty: 'easy' },
  { word: 'dog', difficulty: 'easy' },
  { word: 'house', difficulty: 'easy' },
  { word: 'tree', difficulty: 'easy' },
  { word: 'car', difficulty: 'easy' },
  { word: 'fish', difficulty: 'easy' },
  { word: 'ball', difficulty: 'easy' },
  { word: 'star', difficulty: 'easy' },
  { word: 'moon', difficulty: 'easy' },
  { word: 'flower', difficulty: 'easy' },
  { word: 'apple', difficulty: 'easy' },
  { word: 'heart', difficulty: 'easy' },
  { word: 'eye', difficulty: 'easy' },
  { word: 'book', difficulty: 'easy' },
  { word: 'hat', difficulty: 'easy' },
  { word: 'cup', difficulty: 'easy' },
  { word: 'shoe', difficulty: 'easy' },
  { word: 'bird', difficulty: 'easy' },
  { word: 'cloud', difficulty: 'easy' },
  { word: 'rain', difficulty: 'easy' },
  { word: 'cake', difficulty: 'easy' },
  { word: 'boat', difficulty: 'easy' },
  { word: 'door', difficulty: 'easy' },
  { word: 'key', difficulty: 'easy' },
  { word: 'pizza', difficulty: 'easy' },
  { word: 'smile', difficulty: 'easy' },
  { word: 'egg', difficulty: 'easy' },
  { word: 'ice cream', difficulty: 'easy' },
  { word: 'banana', difficulty: 'easy' },
  { word: 'clock', difficulty: 'easy' },
  { word: 'lamp', difficulty: 'easy' },
  { word: 'chair', difficulty: 'easy' },
  { word: 'bed', difficulty: 'easy' },
  { word: 'spoon', difficulty: 'easy' },

  // Medium — more specific concepts, more detail
  { word: 'guitar', difficulty: 'medium' },
  { word: 'airplane', difficulty: 'medium' },
  { word: 'castle', difficulty: 'medium' },
  { word: 'dragon', difficulty: 'medium' },
  { word: 'robot', difficulty: 'medium' },
  { word: 'snowman', difficulty: 'medium' },
  { word: 'pirate', difficulty: 'medium' },
  { word: 'rocket', difficulty: 'medium' },
  { word: 'butterfly', difficulty: 'medium' },
  { word: 'dinosaur', difficulty: 'medium' },
  { word: 'spider', difficulty: 'medium' },
  { word: 'elephant', difficulty: 'medium' },
  { word: 'penguin', difficulty: 'medium' },
  { word: 'volcano', difficulty: 'medium' },
  { word: 'rainbow', difficulty: 'medium' },
  { word: 'treasure', difficulty: 'medium' },
  { word: 'camera', difficulty: 'medium' },
  { word: 'bicycle', difficulty: 'medium' },
  { word: 'umbrella', difficulty: 'medium' },
  { word: 'sandwich', difficulty: 'medium' },
  { word: 'hamburger', difficulty: 'medium' },
  { word: 'lighthouse', difficulty: 'medium' },
  { word: 'waterfall', difficulty: 'medium' },
  { word: 'telescope', difficulty: 'medium' },
  { word: 'mushroom', difficulty: 'medium' },
  { word: 'campfire', difficulty: 'medium' },
  { word: 'crown', difficulty: 'medium' },
  { word: 'sword', difficulty: 'medium' },
  { word: 'anchor', difficulty: 'medium' },
  { word: 'ladder', difficulty: 'medium' },
  { word: 'bridge', difficulty: 'medium' },
  { word: 'snowflake', difficulty: 'medium' },
  { word: 'helmet', difficulty: 'medium' },
  { word: 'kangaroo', difficulty: 'medium' },
  { word: 'octopus', difficulty: 'medium' },

  // Hard — abstract concepts, challenging to draw
  { word: 'freedom', difficulty: 'hard' },
  { word: 'nightmare', difficulty: 'hard' },
  { word: 'jealousy', difficulty: 'hard' },
  { word: 'gravity', difficulty: 'hard' },
  { word: 'silence', difficulty: 'hard' },
  { word: 'rock music', difficulty: 'hard' },
  { word: 'password', difficulty: 'hard' },
  { word: 'nostalgia', difficulty: 'hard' },
  { word: 'invisible', difficulty: 'hard' },
  { word: 'echo', difficulty: 'hard' },
  { word: 'pollution', difficulty: 'hard' },
  { word: 'evolution', difficulty: 'hard' },
  { word: 'camouflage', difficulty: 'hard' },
  { word: 'power outage', difficulty: 'hard' },
  { word: 'earthquake', difficulty: 'hard' },
  { word: 'headache', difficulty: 'hard' },
  { word: 'sunburn', difficulty: 'hard' },
  { word: 'traffic jam', difficulty: 'hard' },
  { word: 'time travel', difficulty: 'hard' },
  { word: 'sleepwalking', difficulty: 'hard' },
  { word: 'brainwashing', difficulty: 'hard' },
  { word: 'homesickness', difficulty: 'hard' },
  { word: 'backstabbing', difficulty: 'hard' },
  { word: 'brainstorm', difficulty: 'hard' },
  { word: 'scapegoat', difficulty: 'hard' },
];

/** Select the draw-words bank for a language (English falls through to the
 *  EN bank; anything else uses the Serbian default). */
export function getDrawWordBank(lang: Language): DrawWord[] {
  return lang === 'en' ? DRAW_WORD_BANK_EN : DRAW_WORD_BANK;
}
