export interface DrawWord {
  word: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const DRAW_WORD_BANK: DrawWord[] = [
  // Easy — common objects, simple shapes
  { word: 'sun', difficulty: 'easy' },
  { word: 'cat', difficulty: 'easy' },
  { word: 'dog', difficulty: 'easy' },
  { word: 'house', difficulty: 'easy' },
  { word: 'tree', difficulty: 'easy' },
  { word: 'car', difficulty: 'easy' },
  { word: 'fish', difficulty: 'easy' },
  { word: 'ball', difficulty: 'easy' },
  { word: 'star', difficulty: 'easy' },
  { word: 'moon', difficulty: 'easy' },
  { word: 'flower', difficulty: 'easy' },
  { word: 'apple', difficulty: 'easy' },
  { word: 'heart', difficulty: 'easy' },
  { word: 'eye', difficulty: 'easy' },
  { word: 'book', difficulty: 'easy' },
  { word: 'hat', difficulty: 'easy' },
  { word: 'cup', difficulty: 'easy' },
  { word: 'shoe', difficulty: 'easy' },
  { word: 'bird', difficulty: 'easy' },
  { word: 'cloud', difficulty: 'easy' },
  { word: 'rain', difficulty: 'easy' },
  { word: 'cake', difficulty: 'easy' },
  { word: 'boat', difficulty: 'easy' },
  { word: 'door', difficulty: 'easy' },
  { word: 'key', difficulty: 'easy' },
  { word: 'pizza', difficulty: 'easy' },
  { word: 'smile', difficulty: 'easy' },
  { word: 'egg', difficulty: 'easy' },
  { word: 'ice cream', difficulty: 'easy' },
  { word: 'banana', difficulty: 'easy' },
  { word: 'clock', difficulty: 'easy' },
  { word: 'lamp', difficulty: 'easy' },
  { word: 'chair', difficulty: 'easy' },
  { word: 'bed', difficulty: 'easy' },
  { word: 'spoon', difficulty: 'easy' },

  // Medium — more specific, requires a bit more detail
  { word: 'guitar', difficulty: 'medium' },
  { word: 'airplane', difficulty: 'medium' },
  { word: 'castle', difficulty: 'medium' },
  { word: 'dragon', difficulty: 'medium' },
  { word: 'robot', difficulty: 'medium' },
  { word: 'snowman', difficulty: 'medium' },
  { word: 'pirate', difficulty: 'medium' },
  { word: 'rocket', difficulty: 'medium' },
  { word: 'butterfly', difficulty: 'medium' },
  { word: 'dinosaur', difficulty: 'medium' },
  { word: 'spider', difficulty: 'medium' },
  { word: 'elephant', difficulty: 'medium' },
  { word: 'penguin', difficulty: 'medium' },
  { word: 'volcano', difficulty: 'medium' },
  { word: 'rainbow', difficulty: 'medium' },
  { word: 'treasure', difficulty: 'medium' },
  { word: 'camera', difficulty: 'medium' },
  { word: 'bicycle', difficulty: 'medium' },
  { word: 'umbrella', difficulty: 'medium' },
  { word: 'sandwich', difficulty: 'medium' },
  { word: 'hamburger', difficulty: 'medium' },
  { word: 'lighthouse', difficulty: 'medium' },
  { word: 'waterfall', difficulty: 'medium' },
  { word: 'telescope', difficulty: 'medium' },
  { word: 'mushroom', difficulty: 'medium' },
  { word: 'campfire', difficulty: 'medium' },
  { word: 'crown', difficulty: 'medium' },
  { word: 'sword', difficulty: 'medium' },
  { word: 'anchor', difficulty: 'medium' },
  { word: 'ladder', difficulty: 'medium' },
  { word: 'bridge', difficulty: 'medium' },
  { word: 'snowflake', difficulty: 'medium' },
  { word: 'helmet', difficulty: 'medium' },
  { word: 'kangaroo', difficulty: 'medium' },
  { word: 'octopus', difficulty: 'medium' },

  // Hard — abstract concepts, tricky to draw
  { word: 'freedom', difficulty: 'hard' },
  { word: 'nightmare', difficulty: 'hard' },
  { word: 'jealousy', difficulty: 'hard' },
  { word: 'gravity', difficulty: 'hard' },
  { word: 'silence', difficulty: 'hard' },
  { word: 'deadline', difficulty: 'hard' },
  { word: 'password', difficulty: 'hard' },
  { word: 'nostalgia', difficulty: 'hard' },
  { word: 'invisible', difficulty: 'hard' },
  { word: 'echo', difficulty: 'hard' },
  { word: 'pollution', difficulty: 'hard' },
  { word: 'evolution', difficulty: 'hard' },
  { word: 'camouflage', difficulty: 'hard' },
  { word: 'blackout', difficulty: 'hard' },
  { word: 'earthquake', difficulty: 'hard' },
  { word: 'headache', difficulty: 'hard' },
  { word: 'sunburn', difficulty: 'hard' },
  { word: 'traffic jam', difficulty: 'hard' },
  { word: 'time travel', difficulty: 'hard' },
  { word: 'sleepwalk', difficulty: 'hard' },
  { word: 'brainwash', difficulty: 'hard' },
  { word: 'homesick', difficulty: 'hard' },
  { word: 'backstab', difficulty: 'hard' },
  { word: 'brainstorm', difficulty: 'hard' },
  { word: 'scapegoat', difficulty: 'hard' },
];
