// "Ko bi pre..." prompts — everyone votes for a player; whoever matches the
// crowd's top pick scores. Serbian only (the in-game screen is Serbian by
// design); family-friendly.
export const KO_BI_PRE_PROMPTS: string[] = [
  'Ko bi pre zaspao na žurci?',
  'Ko bi pre zaboravio gde je parkirao?',
  'Ko bi pre pojeo poslednje parče pice?',
  'Ko bi pre postao svetski poznat?',
  'Ko bi pre preživeo zombi apokalipsu?',
  'Ko bi pre zakasnio na svoje venčanje?',
  'Ko bi pre potrošio celu platu za jedan dan?',
  'Ko bi pre zaboravio nečije ime odmah po upoznavanju?',
  'Ko bi pre otišao na put bez plana?',
  'Ko bi pre plakao na filmu?',
  'Ko bi pre postao predsednik?',
  'Ko bi pre pao dok hoda i gleda u telefon?',
  'Ko bi pre pojeo nešto što je palo na pod?',
  'Ko bi pre pobedio u rijaliti šou programu?',
  'Ko bi pre zaboravio rođendan najboljeg druga?',
  'Ko bi pre započeo svađu oko gluposti?',
  'Ko bi pre postao milioner?',
  'Ko bi pre pojeo najljuću papričicu za opkladu?',
  'Ko bi pre pričao sam sa sobom?',
  'Ko bi pre otišao na Mars?',
  'Ko bi pre zaboravio ključeve u stanu?',
  'Ko bi pre pao u san usred razgovora?',
  'Ko bi pre napravio najbolji žurku?',
  'Ko bi pre kupio nešto potpuno nepotrebno?',
  'Ko bi pre pobegao od pauka vrišteći?',
  'Ko bi pre pojeo doručak za večeru?',
  'Ko bi pre izgubio u svađi sa detetom?',
  'Ko bi pre postao poznati jutjuber?',
  'Ko bi pre zaboravio da ugasi ringlu?',
  'Ko bi pre pevao naglas u autu?',
  'Ko bi pre preskočio red bez ustručavanja?',
  'Ko bi pre poslao poruku pogrešnoj osobi?',
  'Ko bi pre napisao knjigu?',
  'Ko bi pre završio poslednji sa jelom?',
  'Ko bi pre usvojio deset mačaka?',
  'Ko bi pre zaspao u bioskopu?',
  'Ko bi pre zaboravio šta je hteo da kaže usred rečenice?',
  'Ko bi pre organizovao iznenadno putovanje?',
  'Ko bi pre pojeo tuđu hranu iz frižidera?',
  'Ko bi pre postao profesionalni sportista?',
];
