// "Ko bi pre..." prompts — everyone votes for a player; whoever matches the
// crowd's top pick scores. Serbian only (the in-game screen is Serbian by
// design); family-friendly.
export const KO_BI_PRE_PROMPTS: string[] = [
  'Ko bi pre zaspao na žurci?',
  'Ko bi pre zaboravio gde je parkirao?',
  'Ko bi pre pojeo poslednje parče pice?',
  'Ko bi pre postao svetski poznat?',
  'Ko bi pre preživeo zombi apokalipsu?',
  'Ko bi pre zakasnio na svoje venčanje?',
  'Ko bi pre potrošio celu platu za jedan dan?',
  'Ko bi pre zaboravio nečije ime odmah po upoznavanju?',
  'Ko bi pre otišao na put bez plana?',
  'Ko bi pre plakao na filmu?',
  'Ko bi pre postao predsednik?',
  'Ko bi pre pao dok hoda i gleda u telefon?',
  'Ko bi pre pojeo nešto što je palo na pod?',
  'Ko bi pre pobedio u rijaliti šou programu?',
  'Ko bi pre zaboravio rođendan najboljeg druga?',
  'Ko bi pre započeo svađu oko gluposti?',
  'Ko bi pre postao milioner?',
  'Ko bi pre pojeo najljuću papričicu za opkladu?',
  'Ko bi pre pričao sam sa sobom?',
  'Ko bi pre otišao na Mars?',
  'Ko bi pre zaboravio ključeve u stanu?',
  'Ko bi pre pao u san usred razgovora?',
  'Ko bi pre napravio najbolju žurku?',
  'Ko bi pre kupio nešto potpuno nepotrebno?',
  'Ko bi pre pobegao od pauka vrišteći?',
  'Ko bi pre pojeo doručak za večeru?',
  'Ko bi pre izgubio u svađi sa detetom?',
  'Ko bi pre postao poznati jutjuber?',
  'Ko bi pre zaboravio da ugasi ringlu?',
  'Ko bi pre pevao naglas u autu?',
  'Ko bi pre preskočio red bez ustručavanja?',
  'Ko bi pre poslao poruku pogrešnoj osobi?',
  'Ko bi pre napisao knjigu?',
  'Ko bi pre završio poslednji sa jelom?',
  'Ko bi pre usvojio deset mačaka?',
  'Ko bi pre zaspao u bioskopu?',
  'Ko bi pre zaboravio šta je hteo da kaže usred rečenice?',
  'Ko bi pre organizovao iznenadno putovanje?',
  'Ko bi pre pojeo tuđu hranu iz frižidera?',
  'Ko bi pre postao profesionalni sportista?',
  'Ko bi pre zaboravio telefon u restoranu?',
  'Ko bi pre izgubio novčanik na putovanju?',
  'Ko bi pre zaključao ključeve u autu?',
  'Ko bi pre promašio stanicu jer gleda u telefon?',
  'Ko bi pre prosuo kafu po sebi pred važan sastanak?',
  'Ko bi pre zaboravio da isključi mikrofon na sastanku?',
  'Ko bi pre ušao u pogrešan autobus?',
  'Ko bi pre zalutao u sopstvenom kraju?',
  'Ko bi pre otišao iz kafića ne plativši, pa se vratio trčeći?',
  'Ko bi pre obukao majicu naopako i ne primetio ceo dan?',
  'Ko bi pre uzeo parče torte bez pitanja?',
  'Ko bi pre naručio hranu u tri ujutru?',
  'Ko bi pre pojeo ceo obrok bez ijedne reči?',
  'Ko bi pre probao najčudniju kombinaciju hrane?',
  'Ko bi pre stavio kečap na sve?',
  'Ko bi pre pojeo desert pre glavnog jela?',
  'Ko bi pre zagoreo jelo dok kuva?',
  'Ko bi pre napravio gozbu za dvadeset ljudi?',
  'Ko bi pre popio hladnu kafu i ne primetio?',
  'Ko bi pre uzeo najveće parče?',
  'Ko bi pre pakovao kofer pola sata pre leta?',
  'Ko bi pre poneo tri torbe na jednodnevni izlet?',
  'Ko bi pre propustio avion jer je zaspao?',
  'Ko bi pre otišao na kraj sveta sam?',
  'Ko bi pre izdržao godinu dana bez interneta?',
  'Ko bi pre otišao da živi u drugoj državi?',
  'Ko bi pre spavao pod vedrim nebom?',
  'Ko bi pre zaboravio pasoš kod kuće?',
  'Ko bi pre pristao na put bez povratne karte?',
  'Ko bi pre zalutao u stranom gradu bez mape?',
  'Ko bi pre skočio padobranom?',
  'Ko bi pre ušao sam u kuću duhova?',
  'Ko bi pre plivao sa ajkulama?',
  'Ko bi pre pristao na bandži skok?',
  'Ko bi pre prespavao noć sam u šumi?',
  'Ko bi pre uhvatio miša golim rukama?',
  'Ko bi pre skočio u ledenu vodu?',
  'Ko bi pre prišao nepoznatoj osobi i započeo razgovor?',
  'Ko bi pre izašao na binu bez pripreme?',
  'Ko bi pre pojeo insekta za opkladu?',
  'Ko bi pre održao govor na svadbi?',
  'Ko bi pre zapevao karaoke prvi?',
  'Ko bi pre zaigrao nasred kafića?',
  'Ko bi pre ispričao istu priču po deseti put?',
  'Ko bi pre upoznao ceo kraj za nedelju dana?',
  'Ko bi pre ostao poslednji na žurci?',
  'Ko bi pre otkazao izlazak u poslednji čas?',
  'Ko bi pre pobegao sa žurke bez pozdrava?',
  'Ko bi pre pozvao sve na spontano druženje?',
  'Ko bi pre odgovorio na poruku tek posle nedelju dana?',
  'Ko bi pre kupio nešto samo zato što je na akciji?',
  'Ko bi pre pozajmio novac i zaboravio da vrati?',
  'Ko bi pre častio celo društvo?',
  'Ko bi pre tražio popust na pijaci?',
  'Ko bi pre uložio svu ušteđevinu u ludu ideju?',
  'Ko bi pre dobio na lutriji i nikome ne rekao?',
  'Ko bi pre plaćao pretplatu koju uopšte ne koristi?',
  'Ko bi pre kupio poklon u poslednjem trenutku?',
  'Ko bi pre delio račun na dinar?',
  'Ko bi pre potrošio pola plate na hranu?',
  'Ko bi pre razbio telefon prve nedelje?',
  'Ko bi pre imao sto otvorenih tabova?',
  'Ko bi pre zaboravio lozinku pet minuta pošto ju je postavio?',
  'Ko bi pre odgovorio na poruku jednim slovom?',
  'Ko bi pre poslao glasovnu poruku od pet minuta?',
  'Ko bi pre slikao hranu pre nego što je proba?',
  'Ko bi pre ostao bez baterije u najgorem trenutku?',
  'Ko bi pre odgledao celu seriju u jednom danu?',
  'Ko bi pre pisao komentar ispod svake objave?',
  'Ko bi pre obrisao društvene mreže na mesec dana?',
  'Ko bi pre zaspao na predavanju?',
  'Ko bi pre uradio sve zadatke poslednje noći?',
  'Ko bi pre postao šef za godinu dana?',
  'Ko bi pre dao otkaz i otvorio kafić?',
  'Ko bi pre zaboravio na zakazani sastanak?',
  'Ko bi pre napravio najlepšu prezentaciju bez sadržaja?',
  'Ko bi pre radio do kasno u noć?',
  'Ko bi pre uzeo slobodan dan bez razloga?',
  'Ko bi pre naučio novi jezik iz zabave?',
  'Ko bi pre postao profesor?',
  'Ko bi pre ostavio sudove da stoje tri dana?',
  'Ko bi pre preuredio ceo stan u jednom popodnevu?',
  'Ko bi pre zaboravio veš u mašini?',
  'Ko bi pre zaboravio da zalije cveće?',
  'Ko bi pre sve popravljao sam umesto da zove majstora?',
  'Ko bi pre napravio nered dok traži jednu jedinu stvar?',
  'Ko bi pre imao savršeno uredan radni sto?',
  'Ko bi pre okačio sliku krivo i ostavio je tako?',
  'Ko bi pre kupio nameštaj koji ne staje kroz vrata?',
  'Ko bi pre proveo ceo dan u pidžami?',
  'Ko bi pre doneo kući psa lutalicu?',
  'Ko bi pre pričao sa ljubimcem kao sa čovekom?',
  'Ko bi pre pobegao od pčele preko celog dvorišta?',
  'Ko bi pre nahranio sve golubove u parku?',
  'Ko bi pre nabavio papagaja koji ga imitira?',
  'Ko bi pre zasadio baštu i zaboravio na nju?',
  'Ko bi pre zaplakao zbog filma o životinjama?',
  'Ko bi pre spasavao mačku sa drveta?',
  'Ko bi pre postao veterinar?',
  'Ko bi pre držao zmiju kao ljubimca?',
  'Ko bi pre priznao grešku prvi?',
  'Ko bi pre oprostio i bez izvinjenja?',
  'Ko bi pre pomogao neznancu na ulici?',
  'Ko bi pre rekao istinu i kad boli?',
  'Ko bi pre ćutao da ne povredi nekoga?',
  'Ko bi pre stao u odbranu prijatelja?',
  'Ko bi pre poklonio poslednje što ima?',
  'Ko bi pre zapamtio sitan detalj o svakome?',
  'Ko bi pre oprostio dug?',
  'Ko bi pre priznao pred svima da je pogrešio?',
  'Ko bi pre udario u staklena vrata?',
  'Ko bi pre uzvratio mahanje osobi koja maha nekom iza njega?',
  'Ko bi pre pao na ravnom?',
  'Ko bi pre punim glasom pevao pogrešne reči pesme?',
  'Ko bi pre pomešao imena dvoje ljudi?',
  'Ko bi pre pričao punih usta?',
  'Ko bi pre prasnuo u smeh u pogrešnom trenutku?',
  'Ko bi pre zaboravio poentu vica?',
  'Ko bi pre ispustio telefon sebi na lice dok leži?',
  'Ko bi pre sipao sok pored čaše?',
  'Ko bi pre prevrnuo tablu kad gubi?',
  'Ko bi pre varao u društvenoj igri?',
  'Ko bi pre pobedio u takmičenju u jelu?',
  'Ko bi pre pristao na svaku opkladu?',
  'Ko bi pre odustao na pola trke?',
  'Ko bi pre naučio pravila igre tek u toku igre?',
  'Ko bi pre bio poslednji u kvizu, a najglasniji?',
  'Ko bi pre pobedio u nadmudrivanju pogledom?',
  'Ko bi pre igrao istu igru sto puta zaredom?',
  'Ko bi pre najglasnije slavio pobedu?',
  'Ko bi pre postao svemirski turista?',
  'Ko bi pre živeo u zamku bez struje?',
  'Ko bi pre pristao da mu drugi čitaju misli?',
  'Ko bi pre izabrao da bude nevidljiv?',
  'Ko bi pre otputovao kroz vreme u prošlost?',
  'Ko bi pre razgovarao sa vanzemaljcima?',
  'Ko bi pre postao superheroj sa beskorisnom moći?',
  'Ko bi pre proveo mesec dana na pustom ostrvu?',
  'Ko bi pre zamenio život sa slavnom osobom?',
  'Ko bi pre poverovao u najluđu teoriju?',
  'Ko bi pre ustao u pet ujutru bez alarma?',
  'Ko bi pre odložio alarm deset puta?',
  'Ko bi pre popio pet kafa u toku dana?',
  'Ko bi pre ostao budan celu noć bez razloga?',
  'Ko bi pre počeo da vežba pa odustao za nedelju dana?',
  'Ko bi pre pravio spisak baš za sve?',
  'Ko bi pre odložio sve za sutra?',
  'Ko bi pre stizao svuda pola sata ranije?',
  'Ko bi pre zaboravio da jede jer je zauzet?',
  'Ko bi pre zapamtio ceo raspored napamet?',
  'Ko bi pre zauzeo daljinski za celo veče?',
  'Ko bi pre gledao isti film po deseti put?',
  'Ko bi pre svima otkrio kraj filma?',
  'Ko bi pre zaspao pred televizorom?',
  'Ko bi pre znao tekst svake pesme sa radija?',
  'Ko bi pre plesao sam u sobi?',
  'Ko bi pre iz čista mira počeo da uči da svira?',
  'Ko bi pre napravio plejlistu za svaku priliku?',
  'Ko bi pre pevao u kupatilu punim glasom?',
  'Ko bi pre postao radijski voditelj?',
  'Ko bi pre zvao mamu da pita kako se nešto kuva?',
  'Ko bi pre bio miljenik bake i deke?',
  'Ko bi pre pravio najviše nestašluka kao dete?',
  'Ko bi pre sačuvao igračke iz detinjstva?',
  'Ko bi pre ispričao istu porodičnu priču svima?',
  'Ko bi pre postao najstroži roditelj?',
  'Ko bi pre razmazio tuđe dete?',
  'Ko bi pre pobedio rođaka u raspravi za stolom?',
  'Ko bi pre zaboravio da javi porodici da je stigao?',
  'Ko bi pre čuvao porodični recept kao tajnu?',
  'Ko bi pre okitio jelku već u novembru?',
  'Ko bi pre zaboravio da čestita rođendan?',
  'Ko bi pre pripremio poklone mesec dana ranije?',
  'Ko bi pre ostao najduže na slavi?',
  'Ko bi pre držao zdravicu?',
  'Ko bi pre pojeo najviše kolača za praznike?',
  'Ko bi pre organizovao doček za celo društvo?',
  'Ko bi pre zaspao pre ponoći na Novu godinu?',
  'Ko bi pre poklonio nešto što je i sam dobio na poklon?',
  'Ko bi pre ostavio praznične ukrase do marta?',
  'Ko bi pre svirao drugima u saobraćaju?',
  'Ko bi pre vozio pet sati bez pauze?',
  'Ko bi pre zaboravio da natoči gorivo?',
  'Ko bi pre parkirao iz trećeg pokušaja?',
  'Ko bi pre pustio muziku do daske u autu?',
  'Ko bi pre odbio da pita za pravac?',
  'Ko bi pre držao nered u autu?',
  'Ko bi pre pristao da vozi po najgorem vremenu?',
  'Ko bi pre zaboravio gde je ostavio bicikl?',
  'Ko bi pre stao da pomogne nekome pored puta?',
  'Ko bi pre izašao bez jakne po hladnoći?',
  'Ko bi pre zaboravio kišobran baš kad pada kiša?',
  'Ko bi pre uživao u snegu kao dete?',
  'Ko bi pre izgoreo na suncu već prvog dana?',
  'Ko bi pre ušao u more već u aprilu?',
  'Ko bi pre kukao na vrućinu ceo dan?',
  'Ko bi pre napravio sneška prvi?',
  'Ko bi pre proveo ceo dan na plaži bez pomeranja?',
  'Ko bi pre otišao na planinu umesto na more?',
  'Ko bi pre pratio vremensku prognozu svaki dan?',
  'Ko bi pre nosio istu majicu tri dana?',
  'Ko bi pre potrošio sat vremena birajući odeću?',
  'Ko bi pre promenio frizuru iz čista mira?',
  'Ko bi pre obukao nešto neobično na svadbu?',
  'Ko bi pre kupio cipele koje žuljaju jer lepo izgledaju?',
  'Ko bi pre pustio bradu i zaboravio da je skrati?',
  'Ko bi pre nosio šarene čarape uz odelo?',
  'Ko bi pre pozajmio odeću i ne vratio je?',
  'Ko bi pre proveo najviše vremena pred ogledalom?',
  'Ko bi pre izašao u papučama do prodavnice?',
  'Ko bi pre otišao po hleb i vratio se sa punim kesama?',
  'Ko bi pre napravio spisak pa ga zaboravio kod kuće?',
  'Ko bi pre probao sve besplatne uzorke?',
  'Ko bi pre stajao sat vremena u redu zbog popusta?',
  'Ko bi pre vratio kupljenu stvar u prodavnicu?',
  'Ko bi pre naručio nešto preko interneta u tri ujutru?',
  'Ko bi pre kupio istu stvar dva puta?',
  'Ko bi pre menjao porudžbinu tri puta?',
  'Ko bi pre kupio poklon sebi umesto drugome?',
  'Ko bi pre zaboravio kesu sa kupovinom u prodavnici?',
  'Ko bi pre poslao jelo nazad u kuhinju?',
  'Ko bi pre naručio isto što i svi ostali?',
  'Ko bi pre probao jelo sa tuđeg tanjira?',
  'Ko bi pre ostavio najveći bakšiš?',
  'Ko bi pre najglasnije zvao konobara?',
  'Ko bi pre sedeo dva sata uz jednu kafu?',
  'Ko bi pre naručio nešto što ne ume da izgovori?',
  'Ko bi pre platio račun pre nego što ga iko vidi?',
  'Ko bi pre poneo ostatke kući?',
  'Ko bi pre birao restoran za celo društvo?',
  'Ko bi pre pozvao komšiju na kafu?',
  'Ko bi pre pustio preglasnu muziku u deset uveče?',
  'Ko bi pre znao sve novosti iz zgrade?',
  'Ko bi pre pomogao komšiji da unese nameštaj?',
  'Ko bi pre držao vrata lifta svima?',
  'Ko bi pre prijavio nepravdu u kraju?',
  'Ko bi pre pozdravljao svakoga na ulici?',
  'Ko bi pre zapamtio ime svakog konobara u kraju?',
  'Ko bi pre organizovao akciju čišćenja u kvartu?',
  'Ko bi pre pozajmio alat i zaboravio kome?',
  'Ko bi pre pobedio u trci na sto metara?',
  'Ko bi pre navijao najglasnije?',
  'Ko bi pre zaradio povredu na rekreaciji?',
  'Ko bi pre naučio novi sport za nedelju dana?',
  'Ko bi pre gledao utakmicu do kraja iako njegovi gube?',
  'Ko bi pre otišao na trening u šest ujutru?',
  'Ko bi pre prešao maraton hodajući?',
  'Ko bi pre postao trener?',
  'Ko bi pre raspravljao sa sudijom?',
  'Ko bi pre pobedio u obaranju ruku?',
  'Ko bi pre odlagao odlazak kod lekara?',
  'Ko bi pre pio čaj za sve i svašta?',
  'Ko bi pre počeo dijetu u ponedeljak?',
  'Ko bi pre prespavao dvanaest sati?',
  'Ko bi pre tražio simptome na internetu?',
  'Ko bi pre glumio da mu ništa nije?',
  'Ko bi pre popio vitamine svako jutro?',
  'Ko bi pre pobegao od igle?',
  'Ko bi pre uzeo salatu umesto slatkiša?',
  'Ko bi pre otišao pešice umesto autobusom?',
  'Ko bi pre nacrtao nečiji portret za pet minuta?',
  'Ko bi pre napisao pesmu o društvu?',
  'Ko bi pre snimio film o svom danu?',
  'Ko bi pre napravio nešto lepo od otpada?',
  'Ko bi pre počeo novi hobi pa ga napustio?',
  'Ko bi pre okrečio zidove u neobičnu boju?',
  'Ko bi pre glumio u pozorištu?',
  'Ko bi pre pravio ukrase ručno umesto da ih kupi?',
  'Ko bi pre smislio ime za bend?',
  'Ko bi pre fotografisao sve oko sebe?',
  'Ko bi pre pričao najduže bez prekida?',
  'Ko bi pre upao nekome u reč?',
  'Ko bi pre koristio reči koje niko ne razume?',
  'Ko bi pre ispričao vic koji niko ne shvati?',
  'Ko bi pre progovorio strani jezik posle par dana?',
  'Ko bi pre pričao rukama više nego ustima?',
  'Ko bi pre zaćutao u neprijatnoj situaciji?',
  'Ko bi pre rekao naglas ono što svi misle?',
  'Ko bi pre objašnjavao istu stvar tri puta iz početka?',
  'Ko bi pre pobedio u raspravi bez ijednog argumenta?',
  'Ko bi pre odao iznenađenje pre vremena?',
  'Ko bi pre čuvao tuđu tajnu godinama?',
  'Ko bi pre organizovao iznenađenje za nekoga?',
  'Ko bi pre otvorio poklon pre vremena?',
  'Ko bi pre pronašao skriveni poklon u kući?',
  'Ko bi pre napravio najbolju prvoaprilsku šalu?',
  'Ko bi pre nasedao na svaku šalu?',
  'Ko bi pre slučajno saznao iznenađenje?',
  'Ko bi pre prećutao da mu se nešto ne sviđa?',
  'Ko bi pre pustio suzu na iznenađenju?',
  'Ko bi pre vrisnuo u mraku?',
  'Ko bi pre gledao horor sam?',
  'Ko bi pre pobegao od psa koji laje?',
  'Ko bi pre ostao miran usred panike?',
  'Ko bi pre izbegao lift i popeo se stepenicama?',
  'Ko bi pre priznao da se boji visine?',
  'Ko bi pre proveo noć u muzeju?',
  'Ko bi pre poskočio od zvuka u tišini?',
  'Ko bi pre tražio da ga neko sačeka pred vratima?',
  'Ko bi pre poverovao u duhove?',
  'Ko bi pre našao novac na ulici?',
  'Ko bi pre izabrao najsporiji red na kasi?',
  'Ko bi pre dobio nešto u nagradnoj igri?',
  'Ko bi pre stigao tačno kad autobus kreće?',
  'Ko bi pre pogodio broj iz prve?',
  'Ko bi pre razbio čašu na proslavi?',
  'Ko bi pre naleteo na poznanika u drugom gradu?',
  'Ko bi pre izvukao najgori zadatak?',
  'Ko bi pre imao sreće u poslednjem trenutku?',
  'Ko bi pre zaboravio da je nešto osvojio?',
  'Ko bi pre napravio raspored za odmor po satima?',
  'Ko bi pre organizovao putovanje za deset ljudi?',
  'Ko bi pre otkazao rezervaciju dan pre puta?',
  'Ko bi pre imao rezervni plan za sve?',
  'Ko bi pre poneo lekove, punjač i kišobran za svaki slučaj?',
  'Ko bi pre zaboravio da rezerviše smeštaj?',
  'Ko bi pre vodio evidenciju troškova na putovanju?',
  'Ko bi pre pokupio sve što je besplatno na recepciji?',
  'Ko bi pre budio sve ostale ujutru?',
  'Ko bi pre kasnio na svaki dogovor?',
  'Ko bi pre naučio da žonglira?',
  'Ko bi pre pobedio u pantomimi?',
  'Ko bi pre pogodio odgovor bez razmišljanja?',
  'Ko bi pre pravio timove po svom ukusu?',
  'Ko bi pre najduže objašnjavao pravila?',
  'Ko bi pre izmislio novo pravilo usred igre?',
  'Ko bi pre pustio drugoga da pobedi?',
  'Ko bi pre pamtio rezultat od prošlog puta?',
  'Ko bi pre odmah tražio revanš?',
  'Ko bi pre bio najbolji u igri pogađanja?',
  'Ko bi pre zapalio vatru bez upaljača?',
  'Ko bi pre postavio šator za pet minuta?',
  'Ko bi pre pojeo pečurku iz šume?',
  'Ko bi pre otišao na pecanje u zoru?',
  'Ko bi pre stigao prvi na vrh planine?',
  'Ko bi pre preplivao reku?',
  'Ko bi pre prepoznao ptice po pesmi?',
  'Ko bi pre poneo pun ranac hrane na izlet?',
  'Ko bi pre zaspao u ležaljci?',
  'Ko bi pre skupljao kamenčiće sa plaže?',
  'Ko bi pre pokrenuo svoj posao?',
  'Ko bi pre postao gradonačelnik?',
  'Ko bi pre osnovao humanitarnu organizaciju?',
  'Ko bi pre otvorio pekaru?',
  'Ko bi pre postao poznat po nečemu čudnom?',
  'Ko bi pre završio još jedan fakultet?',
  'Ko bi pre živeo od putovanja?',
  'Ko bi pre napravio izum koji niko ne traži?',
  'Ko bi pre postao pisac dečjih priča?',
  'Ko bi pre ostao ovde kad se svi ostali odsele?',
  'Ko bi pre greškom popio tuđu kafu?',
  'Ko bi pre zaboravio ime filma koji upravo gleda?',
  'Ko bi pre pričao sa uređajima u kući?',
  'Ko bi pre skupljao kese i tegle za svaki slučaj?',
  'Ko bi pre otvorio prozor usred zime?',
  'Ko bi pre sklonio nešto na sigurno pa zaboravio gde?',
  'Ko bi pre imao sto fotografija istog prizora?',
  'Ko bi pre uzeo poslednji keks bez pitanja?',
  'Ko bi pre pomerao nameštaj usred noći?',
  'Ko bi pre delio savete koje niko nije tražio?',
];
